# -*-mode:org;coding:utf-8-*-
# Created:  Lungang Fang 2024-05-17

#+TITLE: My Git Configurations
#+AUTHOR: Fang Lungang
#+DATE: 2024-05-17 +1000

* Global git ignore
:PROPERTIES:
:header-args:conf: :tangle ~/.gitignore
:END:

This is global(default) ignore configuration. Modify =repo/.gitignore= for repo
specific ignores.

Refer to https://github.com/github/gitignore for more to ignore.

** backup files
#+begin_src conf
*~
*.swp
#+end_src

** Compilation output
#+begin_src conf
*.elc
*.pyc
*.o
*.class
#+end_src

** Cache generated by various applications
#+begin_src conf
.Trashes
Thumbs.db
#+end_src

* Block pushing certain branches

To avoid accidentally push a branch with sensitive data, we can add a hook to
corresponding repository.

For example, to block myself from pushing =mine= to github, I tangle (write) the
following code snippet into =~/.dotfiles/.git/hooks/pre-push= in with file
permission =o755=.

#+begin_src bash :tangle ~/.dotfiles/.git/hooks/pre-push :tangle-mode o755
  #!/usr/bin/env bash

  branch_blocked=mine

  if grep -q "$branch_blocked"; then
      echo "Branch '$branch_blocked' is blocked by yourself." >&2
      exit 1
  fi
#+end_src

IMPORTANT:
- Ensure this file's permission is correct.
- Manually copy this file to designated directory if you clone the repository to
  a different place as this hook script itself is *not* copied over by =git
  clone=.
