#!/usr/bin/bash

# Copy this file into .git/hooks and make it EXECUTABLE. Then, attempts to push
# the blocked branch ('git push --all' etc.) will fail.

# This way, we can share our dot files but keep all sensitive data in the
# blocked branch without worrying that branch being push mistakenly.

branch_blocked=mine

if grep -q "$branch_blocked"; then
    echo "Branch '$branch_blocked' is blocked by yourself." >&2
    exit 1
fi
