# -*-mode:org; coding:utf-8; time-stamp-pattern:"8/#\\+DATE:[ \t]+%Y-%02m-%02d %5z$" -*-
# Created: Fang Lungang 2024-08-17

#+TITLE: My Terminal Emulator Configurations
#+AUTHOR: Fang Lungang
#+DATE: 2025-11-26 +1100

* Timestamps

#+name: tangle-time-stamp
#+begin_src emacs-lisp :tangle no
(concat user-full-name " " (format-time-string "%Y-%m-%d %5z"))
#+end_src

#+begin_src lua :tangle ~/.wezterm.lua :noweb yes
  -- Created: Fang Lungang 2024-08-17
  -- Updated: <<tangle-time-stamp()>>
#+end_src

* wezterm

** wezterm vs iTerm2

As a Tmux + Emacs user on MacOS, I don't need multiplexer etc.. Hence, for me the main considerations are:
- Pros
  - Configuration file vs GUI only configuration.
    - Version controllable
    - Editing configuration files is faster than navigating through the GUI.
  - Custom hyperlinks
- Cons
  - Unable to copy a wrapped long line as one line.
  - The out of box setting is not as usable as iTerm2 to me.
  - Does not render all fonts nicely. For example, "Andale Mono" is much nicer in iTerm2.

** Start
#+begin_src lua :tangle ~/.wezterm.lua
  local wezterm = require 'wezterm'
  local config = wezterm.config_builder()
#+end_src

** Appearance

*** Window and frame

#+begin_src lua :tangle ~/.wezterm.lua
  config.window_decorations = 'RESIZE'
  config.window_padding = { left = 0, right = 0, top = 0, bottom = 0}
  config.enable_tab_bar = false
#+end_src

*** Fonts

See [[https://github.com/ryanoasis/nerd-fonts/discussions/1103][this post]] for the differences of the 3 variations of nerd fonts, i.e. (nerd
font, nerd font mono, and nerd font propo).

#+begin_src lua :tangle ~/.wezterm.lua
  -- Install the font using "brew install font-dejavu-sans-mono-nerd-font"
  local font_family = 'DejaVuSansM Nerd Font'

  -- Fallback font for missing glyphs (say ) or if the primary font is
  -- unavailable. NOTE: WezTerm has built-in font fallbacks ("JetBrains Mono",
  -- "Noto Color Emoji", "Symbols Nerd Font Mono"). This manual configuration is
  -- unnecessary in most cases but preserved as a reference for future
  -- customization needs.
  local fallback_font = 'JetBrainsMono Nerd Font'

  -- Helper function to create a font object with fallback
  local function font_with_weight(weight)
     return wezterm.font_with_fallback({
           { family = font_family, weight = weight },
           fallback_font,
     })
  end

  -- To apply the rules, assign this local variable to "config.font_rules" below
  local font_rules = {
     -- Change text weight. If the designated weight is unavailable, silently
     -- falls back to the closest one.
     {

        intensity = 'Normal',
        font = font_with_weight('Medium'),
     },
     {
        -- Increase the weight of Bold text
        intensity = 'Bold',
        font = font_with_weight('ExtraBold'),
     },
  }

  config.font = font_with_weight('Regular')
  -- config.font_rules = font_rules
  config.font_size = 19

  -- Ligature settings. The selected font must supports theses features. (Nerd
  -- Fonts does)
  config.harfbuzz_features = {
     -- Contextual Alternates, '->', '!=' etc.
     'calt=1',
     -- Contextual Ligatures
     'clig=0',
     -- Standard Ligatures
     'liga=0',
  }
#+end_src

*** Brightness and colour

#+begin_src lua :tangle ~/.wezterm.lua
  config.foreground_text_hsb = {
     hue = 1.0,
     saturation = 1.0,
     brightness = 0.7,
  }

  config.bold_brightens_ansi_colors = "No"
#+end_src

NOTE: to test ~bold_brightens_ansi_colors~, verify the results in a shell CLI.
Do NOT do it within Emacs, as Emacs themes may apply their own brightness
adjustments that could interfere with the results.

Use the following commands to display bold and normal text with colours:
#+begin_src bash
  echo -e "\e[1;31mBold Red\e[0m vs \e[31mNormal Red\e[0m"
  echo -e "\e[1;32mBold Green\e[0m vs \e[32mNormal Green\e[0m"
  echo -e "\e[1;34mBold Blue\e[0m vs \e[34mNormal Blue\e[0m"
  echo -e "\e[1;33mBold Yellow\e[0m vs \e[33mNormal Yellow\e[0m"
#+end_src

*** COMMENT Opacity

#+begin_src lua :tangle ~/.wezterm.lua
  config.window_background_opacity = 0.8
#+end_src
This is interesting, but I often prefer to disable it as the background can be
distracting.

Additionally, for Emacs running in the terminal to support opacity, set its
background to "unspecified-bg" as shown below:
#+begin_src emacs-lisp
  (set-face-background 'default "unspecified-bg")
#+end_src

** Audible Bell
This is needed because audible bell is *not* affected by the system audio volume.
#+begin_src lua :tangle ~/.wezterm.lua
  config.audible_bell = "Disabled"
#+end_src

** Keyboard
#+begin_src lua :tangle ~/.wezterm.lua
  -- Do not set left/right "Alt as "AltGr"
  config.send_composed_key_when_left_alt_is_pressed = false
  config.send_composed_key_when_right_alt_is_pressed = false

  config.disable_default_key_bindings = true
  config.native_macos_fullscreen_mode = true

  config.keys = {
     { action = wezterm.action.CloseCurrentTab {confirm = true}, key = 'w', mods = 'CMD'},
     { action = wezterm.action.QuitApplication, key = 'q', mods = 'CMD'},
     { action = wezterm.action.Hide, key = 'h', mods = 'CMD'},
     { action = wezterm.action.SpawnWindow, key = 'n', mods = 'CMD'},

     { action = wezterm.action.DecreaseFontSize, key = '-', mods = 'CMD'},
     { action = wezterm.action.IncreaseFontSize, key = '=', mods = 'CMD'},

     { action = wezterm.action.PasteFrom 'Clipboard' , key = 'v', mods = 'CMD', },
     { action = wezterm.action.PasteFrom 'PrimarySelection', key = 'v', mods = 'CMD', },
     { action = wezterm.action.ToggleFullScreen, key = 'f', mods = 'CMD|CTRL',},
  }
#+end_src

** Custom hyperlinks
#+begin_src lua :tangle ~/.wezterm.lua
  -- Use the defaults as a base
  config.hyperlink_rules = wezterm.default_hyperlink_rules()
  table.insert(
     config.hyperlink_rules,
     {
        -- example: clicking on SERVER-1234 opens this mongodb sever ticket
        regex = [[\b((SERVER|server)-[0-9]+)\b]],
        format = 'https://jira.mongodb.org/browse/$1'
     }
  )
#+end_src

** Return the config object (end of the config)
#+begin_src lua :tangle ~/.wezterm.lua
  return config
#+end_src
