#!/usr/bin/env sh

# Created: Lungang Fang 2024-01-22
# Modified: Lungang Fang 2024-01-25T11:33:40+1100>

# Install
# brew install koekeishiya/formulae/yabai
# brew install koekeishiya/formulae/skhd
# yabai --start-service
# skhd --start-service

# MacOS System Settings
# > Desktop & Dock
#   - Automatically hide and show the Dock - on
#   - Automatically rearrange Spaces based on most recent use - off
#

# Float windows, i.e. windows Yabai shouldn't manage
yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-Elements$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" sticky=on layer=above manage=off
# yabai -m rule --add app="^Finder$" sticky=on layer=above manage=off

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  06
yabai -m config bottom_padding               06
yabai -m config left_padding                 06
yabai -m config right_padding                06
yabai -m config window_gap                   06

echo "yabai configuration loaded.."
