#!/usr/bin/env bash
# Created: Lungang Fang 2024-01-25
# Modified: Lungang Fang 2024-01-25T21:45:15+1100>

set -o errexit
set -o pipefail

target="$1"
if [ "$target" == "west" ]; then
    opposite="east"
    window_placement="second_child"
elif [ "$target" == "east" ]; then
    opposite="west"
    window_placement="first_child"
else
    echo "Unspported direction '$target'" >&2
    exit 1
fi

if [ "$(yabai -m query --windows --display "$target" | jq 'length')" == "0" ]; then
    # The other display has no window to swap, just move the current window to it.
    yabai -m window --display "$target"
else
    # the other display has window(s), swap the one next to the display border

    cur_win=$(yabai -m query --windows --window | jq '.id')

    # move to the next display
    yabai -m display --focus "$target"

    # find the window on the border
    while yabai -m window --focus "$opposite" 2>/dev/null; do
        true
    done

    to_swap=$(yabai -m query --windows --window | jq '.id')
    original_window_placement=$(yabai -m config window_placement)

    yabai -m config window_placement "$window_placement"
    yabai -m window "$to_swap" --swap "$cur_win"
    yabai -m config window_placement "$original_window_placement"
    yabai -m window --focus "$cur_win"
fi
